2024-07-18 14:50:08,889 - INFO - {"event": "join", "login": "Данил"}
2024-07-18 14:50:16,818 - INFO - {"event": "join", "login": "Яна"}
2024-07-18 14:50:19,374 - INFO - {"event": "message", "text": "Хеллоу", "login": "Яна"}
2024-07-18 14:50:20,977 - INFO - {"event": "message", "text": "Привет", "login": "Яна"}
2024-07-18 14:50:25,660 - INFO - {"event": "message", "text": "Как дела?", "login": "Данил"}
2024-07-18 14:50:30,728 - INFO - {"event": "message", "text": "Хорошо, ты как?", "login": "Данил"}
2024-07-18 14:50:32,580 - INFO - {"event": "message", "text": "quit", "login": "Данил"}
2024-07-18 14:50:32,580 - INFO - {"event": "leave", "login": "Данил"}
2024-07-18 14:50:35,831 - INFO - {"event": "message", "text": "quit", "login": "Яна"}
2024-07-18 14:50:35,831 - INFO - {"event": "leave", "login": "Яна"}
2024-07-18 14:50:35,831 - ERROR - Error in broadcaster: Set of Tasks/Futures is empty.
2024-07-18 14:50:52,458 - INFO - Сервер завершил работу
2024-07-18 15:06:36,977 - ERROR - Error in handle_chat_client (outer): 'NoneType' object has no attribute 'error'
2024-07-18 15:06:47,200 - ERROR - Error in handle_chat_client (outer): 'NoneType' object has no attribute 'error'
2024-07-18 15:06:56,287 - INFO - Сервер завершил работу
2024-07-18 15:08:05,418 - INFO - {"event": "join", "login": "f"}
2024-07-18 15:08:07,304 - INFO - {"event": "message", "text": "sa", "login": "f"}
2024-07-18 15:08:10,439 - ERROR - Error in handle_chat_client (outer): name 'logger' is not defined
2024-07-18 15:08:50,464 - ERROR - Error in write_message: 
2024-07-18 15:08:50,464 - INFO - Сервер завершил работу
2024-07-18 15:08:50,471 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<ChatServer.handle_chat_client() done, defined at C:\Users\Fentipluh\PycharmProjects\w11_test\server.py:99> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "C:\Users\Fentipluh\PycharmProjects\w11_test\server.py", line 138, in <module>
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Program Files\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Fentipluh\PycharmProjects\w11_test\server.py", line 106, in handle_chat_client
    async def main():
                      
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
